### ISSUE TITLE
Production environment specific problem - Invalid Site

### ISSUE THREAD

**Issue by luyzdeleon** [Shopify/omniauth-shopify-oauth2#30]
I am running a heroku app with this gem installed in a production environment, the problem is that only in this environment when the oauth calls finishes and the store user authenticates the app, the validation here: https://github.com/Shopify/omniauth-shopify-oauth2/blob/master/lib/omniauth/strategies/shopify.rb#L27, returns false.

This only happens when running production environment on heroku, while running production environment on my local machine works fine.

Btw, i am using cloudflare for DNS and when i route the redirect_uri from my cloudflare dns (e.g. example.com) it doesn't work, but when i do it via the herokuapp subdomain (e.g. myapp.herokuapp.com) it works, and valid_site? returns true.

**Comment by luyzdeleon** [comment]
Found the issue within my own DNS configuration, sorry.

**Comment by Shine18** [comment]
luyzdeleon can you please tell me how did you solve it with DNS?

**Comment by luyzdeleon** [comment]
@Shine18 I created an alias CNAME record that always redirects to our www subdomain, that way it always resolves.
