### ISSUE TITLE
can't find admin info

### ISSUE THREAD

**Issue by Skaelv** [Shopify/omniauth-shopify-oauth2#46]
I need to know basic informations about the admin which authenticated with my app but those informations do not seem to be in `request.env['omniauth.auth']`.
What is the best way to get those infos after authentication ?

**Comment by EiNSTeiN-** [comment]
There is no way to do this currently. We're working on a way to authenticate users independently, but this is not available to application developers yet. Currently apps only have access to the shop domain, not individual user information.

**Comment by Skaelv** [comment]
Nevertheless it is a requirement to publish an app ? 
I have a signup form in my app and your Apps Onboarder told me that I need to pre-populate my form with user info from authentication.

**Comment by EiNSTeiN-** [comment]
I'm not sure where the confusion comes from, but I can confirm that there's no way to do this currently. You should be able to grab the shop owner name and email from here though: https://help.shopify.com/api/reference/shop
