### ISSUE TITLE
running to server

### ISSUE THREAD

**Issue by MassMadankumar** [Shopify/omniauth-shopify-oauth2#62]
root@instance-2:/mnt/zapstore.com/shopifyapp/zap# rails s
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run `rails server -h` for more startup options
Puma starting in single mode...
* Version 3.11.0 (ruby 2.4.2-p198), codename: Love Song
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2017-12-18 06:10:58 +0000 ===
- Goodbye!
Exiting

**Comment by dylanahsmith** [comment]
What is the issue?  It looks like you started the server then stopped it with Ctrl-C without problems.
